#!/usr/bin/env bash
# Writes .env (git-ignored) with fresh random secrets for docker compose. Refuses to overwrite an existing file, because
# rotating POSTGRES_PASSWORD or VAULT_MASTER_KEYS under a running stack would lock it out of its own data.
#   bash scripts/development/docker-secrets.sh [--force]
set -euo pipefail
cd "$(dirname "$0")/../.."

if [ -f .env ] && [ "${1:-}" != "--force" ]; then
  echo ".env already exists; not overwriting (use --force to replace it and lose access to existing data)" >&2
  exit 0
fi

hex() { openssl rand -hex "$1"; }
umask 077
cat > .env <<EOF
# Generated by scripts/development/docker-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). NEVER commit this file.
POSTGRES_PASSWORD=$(hex 24)
APP_DB_PASSWORD=$(hex 24)
API_KEY_HASH_PEPPER=$(hex 32)
JWT_ACCESS_SECRET=$(hex 32)
SECURITY_ENGINE_TOKEN=$(hex 24)
DOCUMENT_SCANNER_TOKEN=$(hex 24)
VAULT_TOKEN=$(hex 24)
REDIS_PASSWORD=$(hex 24)
VAULT_MASTER_KEYS=k1:$(openssl rand -base64 32)
PROVIDER_CREDENTIAL_KEYS=p1:$(openssl rand -base64 32)
# Optional providers (leave empty to disable):
GEMINI_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
OLLAMA_BASE_URL=
OLLAMA_MODEL=
EOF
echo "wrote .env with fresh secrets (mode 600)"
