// SentinelAI on a local kind cluster - the environment used to actually run and verify the Terraform path
// (scripts/development/k8s-verify.sh --terraform). It is also the smallest complete example of using the module.
//
//   kind create cluster --name sentinel-verify
//   kind load docker-image sentinel-ai/api:local ...        # the locally built images
//   terraform init && terraform apply
//
// Secrets are generated by the module and therefore live in the local state file. That is acceptable for a throwaway
// cluster; production should pass `existing_secret` instead.

terraform {
  required_version = ">= 1.6.0"
  required_providers {
    kubernetes = { source = "hashicorp/kubernetes", version = "~> 2.32" }
    helm       = { source = "hashicorp/helm", version = "~> 2.15" }
  }
}

variable "kube_context" {
  type    = string
  default = "kind-sentinel-verify"
}

variable "kubeconfig_path" {
  type    = string
  default = "~/.kube/config"
}

variable "document_scanner_enabled" {
  description = "ClamAV needs ~3Gi; off by default on a laptop cluster."
  type        = bool
  default     = false
}

provider "kubernetes" {
  config_path    = var.kubeconfig_path
  config_context = var.kube_context
}

provider "helm" {
  kubernetes {
    config_path    = var.kubeconfig_path
    config_context = var.kube_context
  }
}

module "sentinel" {
  source = "../../modules/kubernetes"

  namespace    = "sentinel-tf"
  release_name = "sentinel"
  chart_path   = "${path.module}/../../../helm/sentinel-ai"

  image_tag         = "local"
  image_pull_policy = "Never" // images are side-loaded into the kind nodes

  api_replicas             = 1
  cors_origins             = "http://localhost:3000"
  signup_enabled           = true // the verification script creates organizations through the API
  document_scanner_enabled = var.document_scanner_enabled

  extra_values = {
    securityEngine = { replicas = 1 }
    tokenVault     = { replicas = 1 }
    dashboard      = { replicas = 1 }
  }
}

output "gateway_service" { value = module.sentinel.gateway_service }
output "namespace" { value = module.sentinel.namespace }
output "release_status" { value = module.sentinel.release_status }
